name: pangeo
channels:
 - conda-forge
dependencies:
 - python=3.8*
 - pangeo-notebook=2021.06.05
 - planetary-computer
 - pystac
 - pystac-client
 - r-base
 - r-caret
 - r-data.table
 - r-dendextend
 - r-devtools
 - r-dtwclust
 - r-e1071
 - r-flexclust
 - r-gdalcubes
 - r-gdalutils
 - r-geoR
 - r-geosphere
 - r-ggplot2
 - r-hdf5r
 - r-irkernel
 - r-keras
 - r-kohonen
 - r-lidr
 - r-lubridate
 - r-magrittr
 - r-mass
 - r-mgcv
 - r-ncdf4
 - r-nnet
 - r-proj4
 - r-ptw
 - r-randomfields
 - r-randomforest
 - r-ranger
 - r-raster
 - r-rcolorbrewer
 - r-reticulate
 - r-rgdal
 - r-rgeos
 - r-rlas
 - r-rnetcdf
 - r-rstac
 - r-sf
 - r-signal
 - r-slider
 - r-sp
 - r-spacetime
 - r-spatstat
 - r-spdep
 - r-stars
 - r-sits
 - r-terra
 - r-tidync
 - r-tidyverse
 - r-tmap
 - r-xgboost
 - r-zoo
 # - r-dtwsat  # TODO: package on conda-forge
